'use client'

import React, { useEffect, useState } from 'react'
import { createClient } from '@/utils/supabase'
import { useParams } from 'next/navigation'

export default function OrderSummaryPage() {
  const params = useParams()
  const id = params?.id
  const [order, setOrder] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const supabase = createClient()

  useEffect(() => {
    async function fetchOrder() {
      if (!id) return
      const { data, error } = await supabase
        .from('orders')
        .select('*')
        .eq('id', id)
        .maybeSingle()

      if (error) console.error("Error fetching order:", error)
      else setOrder(data)
      setLoading(false)
    }
    fetchOrder()
  }, [id, supabase])

  if (loading) return <p className="p-8 text-center text-black">Loading summary...</p>
  if (!order) return <p className="p-8 text-center text-red-500">Order not found.</p>

  // Logic to group the snapshot items by store for the printout
  const itemsByStore = order.items.reduce((acc: any, item: any) => {
    acc[item.store_name] = [...(acc[item.store_name] || []), item]
    return acc
  }, {})

  return (
    <div className="min-h-screen bg-white p-8 text-black font-sans max-w-2xl mx-auto border shadow-lg my-8">
      {/* Header */}
      <div className="flex justify-between items-center border-b-4 border-green-600 pb-6 mb-6">
        <div>
          <h1 className="text-3xl font-black text-green-600 uppercase tracking-tight">Save-n-Deliver</h1>
          <p className="text-gray-500 text-sm font-bold uppercase tracking-widest">Delivery Instruction Sheet</p>
        </div>
        <div className="text-right">
          <p className="font-bold">ID: #{String(order.id).slice(0, 8)}</p>
          <p className="text-xs text-gray-400">{new Date(order.created_at).toLocaleDateString()}</p>
        </div>
      </div>

      {/* Instructions */}
      <div className="mb-8 p-4 bg-gray-50 border-l-4 border-gray-300">
        <h2 className="text-sm font-black uppercase mb-1">Shopper Notice:</h2>
        <p className="text-sm text-gray-700 leading-tight">
          Please visit each store section below. Follow the specific item lists to ensure the 
          <strong> ${Number(order.total_price).toFixed(2)}</strong> budget is maintained.
        </p>
      </div>

      {/* Store Groupings */}
      <div className="space-y-8">
        {Object.keys(itemsByStore).map((storeName) => (
          <div key={storeName} className="border border-gray-200 rounded-lg overflow-hidden">
            <div className="bg-gray-800 text-white px-4 py-2 flex justify-between items-center">
              <h3 className="font-bold uppercase text-sm tracking-widest">{storeName}</h3>
              <p className="text-xs opacity-70">Pick up items below</p>
            </div>
            <div className="p-4 space-y-3">
              {itemsByStore[storeName].map((item: any, idx: number) => (
                <div key={idx} className="flex justify-between items-center text-sm">
                  <div className="flex items-center gap-3">
                    <div className="h-4 w-4 border-2 border-gray-300 rounded"></div> {/* Checkbox for printout */}
                    <span className="font-medium">{item.product_name}</span>
                  </div>
                  <span className="font-mono font-bold">${Number(item.price).toFixed(2)}</span>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* Total Section */}
      <div className="mt-12 text-center border-t-2 border-gray-100 pt-8">
        <p className="text-xs text-gray-400 uppercase font-bold mb-1">Grand Total for All Stores</p>
        <p className="text-4xl font-black text-green-600">${Number(order.total_price).toFixed(2)}</p>
        
        <button 
          onClick={() => window.print()} 
          className="mt-8 bg-green-600 text-white px-10 py-3 rounded-full font-black uppercase tracking-widest hover:bg-green-700 shadow-xl transition print:hidden"
        >
          Print for Delivery
        </button>
      </div>

      <p className="hidden print:block text-[10px] text-gray-300 text-center mt-10">
        Generated by Save-n-Deliver App. Thank you for shopping smart!
      </p>
    </div>
  )
}
